INSERT INTO PROJECTS(PROJECT_ID, PROJECT_NAME) VALUES (1, 'ERP')
INSERT INTO PROJECTS(PROJECT_ID, PROJECT_NAME) VALUES (2, 'Sales CRM')

INSERT INTO MEMBERS(MEMBER_ID, MEMBER_NAME, PROJECT_ID) VALUES (1, 'John Does', 1)
INSERT INTO MEMBERS(MEMBER_ID, MEMBER_NAME, PROJECT_ID) VALUES (2, 'Jane Does', 1)
INSERT INTO MEMBERS(MEMBER_ID, MEMBER_NAME, PROJECT_ID) VALUES (3, 'Jack Danie', null)