SELECT PROJECT_NAME, MEMBER_NAME
FROM MEMBERS
FULL OUTER JOIN PROJECTS ON PROJECTS.PROJECT_ID = MEMBERS.PROJECT_ID
ORDER BY MEMBER_NAME;

SELECT PROJECT_NAME, MEMBER_NAME
FROM MEMBERS
LEFT JOIN PROJECTS ON PROJECTS.PROJECT_ID = MEMBERS.PROJECT_ID
ORDER BY MEMBER_NAME;