CREATE TABLE CLIENTE_01
(A01_CODIGO NUMBER(5) PRIMARY KEY,
A01_NOME VARCHAR(40) NOT NULL,
A01_ENDERECO VARCHAR(40) NOT NULL,
A01_CPF CHAR(11) NOT NULL UNIQUE
);

CREATE TABLE NOTA_02
(A02_CODIGO NUMBER(5) PRIMARY KEY,
A02_DATA DATE NOT NULL,
A02_VALOR_TOTAL NUMBER(2) NOT NULL,
A01_CODIGO NUMBER(5) NOT NULL,
FOREIGN KEY (A01_CODIGO) REFERENCES CLIENTE_01(A01_CODIGO)
);

CREATE TABLE ESTOQUE_03
(A03_CODIGO NUMBER(5) PRIMARY KEY,
A03_DESCRICAO VARCHAR(40) NOT NULL,
A03_VALOR_UNITARIO NUMBER(2) NOT NULL
);

CREATE TABLE ITEM_04
(A04_CODIGO NUMBER(5) PRIMARY KEY,
A04_QTD NUMBER(5) NOT NULL,
A04_VALOR_ITEM NUMBER(2) NOT NULL,
A02_CODIGO NUMBER(5) NOT NULL,
A03_CODIGO NUMBER(5) NOT NULL,
FOREIGN KEY (A02_CODIGO) REFERENCES NOTA_02(A02_CODIGO),
FOREIGN KEY (A03_CODIGO) REFERENCES ESTOQUE_03(A03_CODIGO)
);



